eps = """
Towards a Deeper Understanding of Rent Stabilization and Prop 10, with Yonathan Randolph 2018-10-04 at 9:00 AM Rent stabilization may seem simple, but as Yonathan Randolph lays out in his recent article, it interacts with a body of legal precedent that reflects what "fair rate of return" a landlord shall receive. What exactly does this mean for rent stabilization programs, and how does this compare to other powers (such as that to tax) to take land rents away from landlords?  
Jordan Grimes on San Mateo's Housing Deficit and its Homeowner Anger 2018-08-02 at 9:00 AM Jordan Grimes is an activist for housing and transporation in San Mateo, where efforts to add housing capacity are often met with hostility from homeowners, who often trace the city's problems to an influx of tech workers. Jordan, though, is a San Matean born and raised. Paul Leone also joins the program to talk about how San Mateo thwarts affordable housing. We talk process and policy, including the extension of Measure P, to set a hard limit on possible density.  
The Palo Alto Process and the (Im)morality of Developers, with Max Kapczynski 2018-04-19 at 9:00 AM Max Kapczynski of Palo Alto Forward is back, to talk about recent goings-on in Palo Alto. An affordable housing overlay made its way through council, but what does it *really* mean about the housing situation at large. We expand this into a conversation about developers, and how money is made. Some claim they're no different than anybody else offering a service, and some claim that their form of making money is inherently immoral. Who's right?  
Talking the PPP Social Housing Paper with Asn Ndiaye 2018-04-12 at 9:00 AM We talk with Asn Ndiaye about what leftist housing policy means, analyze the PPP Social Housing policy paper that everybody's talking about, and find time to discuss the importance of real estate in Sex and the City.  
Christine Peterson of the Foresight Institute: Vision Week 2017-11-24 at 5:00 PM We talk positive and negative visions of the future with the founder of the Foresight Institute, Christine Peterson. The Foresight Institute holds a conference looking forward to future technology and society: Vision Week, held December 2-3, 2017.
Roundtable on Fairness and Idealism 2017-10-20 at 5:00 PM Mark and Jake start off talking about Esperanto for 20 seconds, and then get into a long discussion about the power of idealism, and how central the role of fairness is in popular consciousness.
Diego Aguilar-Canabal on Disaster and Inequity in Puerto Rico 2017-10-06 at 5:00 PM Diego Aguilar-Canabal (of East Bay Forward) isn't here to talk about housing, but rather the disaster in Puerto Rico, how it has personally affected his family, and the unfair policies that continually works against the US Territory.
Matt Krisiloff on Y Combinator, Basic Income, and LVT on the United Slate 2017-08-01 at 10:00 AM We have Matt Krisiloff of YC Research to talk about the Basic Income project, Y Combinator's United Slate (which featured LVT as a plank). Should these be viewed as separate, or two ideas that are fundamentally linked? Also a conversation with Kedar about the technical and moral merits of a UBI versus a Jobs Guarantee.
Steve Omohundro on AI Risk, Human Values, and Decentralized Resource Sharing 2017-07-18 at 10:00 AM Steve Omohundro shares plans for creating provably correct protections against AI superintelligence, and thoughts on how human values can be embued into AI. Resource allocation, decentralized cooperation, and discussions on how Blockchain Proofs of Work/Stake can possibly be compatible with basic needs.  
SF Supervisor Katy Tang and Home-SF 2017-06-27 at 10:00 AM Katy Tang represents the Sunset on the SF Board of Supervisors, and has led Home-SF, which works to end displacement while still building more units, by tying affordability to upzoning incentives. We talk about ending zero-sum thinking.
James K. Galbraith on inequality 2017-06-20 at 10:00 AM James K. Galbraith has produced a deep catalogue of books; in his recent "Inequality: What Everyone Needs to Know", he touches on the land value tax. We talk about that and much more.
Jeff Andrade-Fong and Josh Vincent on Influencing Housing Policy 2017-06-13 at 10:00 AM Jeff Andrade-Fong works with Tech for Housing to bring attention to tech workers about how housing policy affects them, and what they can do. Josh Vincent advises land policy on a city-by-city basis using open data and more. Changing policy is hard, but we talk about what people can do about it.
Stephen Barton and the Berkeley Landlord Tax 2017-05-30 at 10:00 AM Last November, Berkeley passed Measure U1, nicknamed the "Landlord Tax." It increased the tax rate for landlords of five or more rental units. Behind the bill was Stephen Barton, who's been working for affordable housing for decades. On the side, he's been writing about the Georgist history of Berkeley's leadership.
Economy of Cities with Kedar 2017-05-16 at 10:00 AM Kedar is back to talk about mobility. We have depressed economies and cities with excess demand. Why?
Corey Smith of SFHAC 2017-05-09 at 10:00 AM Corey Smith of the San Francisco Housing Action Coalition talks about the policies and the politics to get the housing supply up to 5,000 units a year. All your favorites are here: CEQA and Prop 13. Some talk about the limits of empathy: are our land-use policies making us meaner?
James Hughes: Technoprogressivism 2017-05-02 at 10:00 AM We featured the libertarian transhumanist perspective of Zoltan Istvan a few weeks ago. Today, James Hughes, who couples a concern for transhumanism with a progressive attitude and a focus on economic justice.
Introduction to Georgism with Kedar 2017-04-25 at 10:00 AM Kedar and Mark have a conversation about Georgism, Prop 13, and why this all matters.
Zoltan Istvan: Funding a UBI 2017-04-18 at 10:00 AM Zoltan Istvan ran for President on the Transhumanist party, and is now running for California Governor as a Libertarian. He proposes a Universal Basic Income, funded by the leasing of federal lands. How does this compare to the Georgist ideal of a citizen's dividend funded by land rents?
Urban economics of the Asian Tigers 2017-04-11 at 10:00 AM Mark Mollineaux, Jacob Schwartz-Lucas, and Edward Miller discuss the land-use policies of Hong Kong, Singapore, Taiwan and more. How responsible is municipal ownership to land to the world-class infrastructure and vibrant economies of these cities?
"""
import random
eps = [x for x in eps.splitlines() if x]
print(random.choice(eps))
